### ISSUE TITLE
Pre-Requisites in readme should include gulp

### ISSUE THREAD

**Issue by fe01134** [hanyelemary/tdd-react-redux-isomorphic#1]
Thanks for your example/video.  I did have trouble finding the links to the examples.  They were at the end of the tutorial video rather than at the begining :(.

It would be helpful if you also referenced:
https://semantic-ui.com/introduction/getting-started.html
as a pre-requisite. I got error gulp: command not found

**Comment by anthonybrown** [comment]
I just got sick of looking for the files so I looked the author up by name. Thanks for the link to semantic-ui

**Comment by hanyelemary** [comment]
Hi folks, thanks for the feedback. I'll update the README to include gulp and reference semantic-ui. Appreciate the helpful feedback.

**Comment by hanyelemary** [comment]
I just added Gulp and SemanticUI to the Tech Stack section of the README and linked to SemanticUI's website. Keep the helpful feedback coming! Thanks again.
