### ISSUE TITLE
Cannot NPM Install

### ISSUE THREAD

**Issue by rogerza** [hanyelemary/tdd-react-redux-isomorphic#2]
Which version of Node should be used? I am getting installation errors for package `wrench-js`, but it's not listed in the `package.json`.

**Comment by hanyelemary** [comment]
I'm using node v7.4.0. Which version are you using? Let me know and I can try to help you debug it.

**Comment by rogerza** [comment]
Thanks! I just tried again with v7.4.0 and still got the error:
```
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm ERR! fetch failed https://github.com/derekslife/wrench-js/tarball/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by hanyelemary** [comment]
Ok, I could reproduce the error on my machine. It looks like the semantic version in package.json was removed. I upgraded to a higher version. Try it now. You should also make sure to run the following command before you run: 

`npm run build:semantic`

This will build the css and javascript for semantic after installing everything in package.json. I updated the readme to reflect the change. Let me know if you're still having problems. Thanks for pointing me to this issue :)

**Comment by rogerza** [comment]
Yep, that did the trick! Love your TDD videos, btw. Thanks again!

**Comment by hanyelemary** [comment]
Awesome. I'm glad that worked for you as I am that you found the TDD videos helpful.
