### ISSUE TITLE
The semantic-ui library cannot be built into the main project

### ISSUE THREAD

**Issue by GooseCoder** [hanyelemary/tdd-react-redux-isomorphic#3]
The npm run build:semantic requires a gulpfile that doesn't exist inside the semantic folder. Without it it's not possible to successfully build the project and follow the tdd under react/redux course. Could you please provide the missing gulpfile?

By the way great course.

Regards

**Comment by hanyelemary** [comment]
Make sure you have gulp installed globally (as in the README.md). `npm install -g gulp` should do the trick.

After that, you should be able to get everything you need by running `npm install` in the main project directory. If that doesn't work, let me know what error you're getting and I'm happy to debug with you.

**Comment by GooseCoder** [comment]
I am terribly sorry, I didn't follow the instructions properly :( , yes the global gulp dependency was a requirement, once I've reinstalled the dependencies again I have the right semantic configuration. I am going to update the ticket to close. Horray!

Thank you again for your excellent course, It was really well structured and helped me a lot to have a quite productive test centered workflow with react and redux. One last thing, maybe you want to update your description of the course in the Safari Online books platform. I've found your course there, but there wasn't a link to this repository, I struggled a little bit trying to find the source code. 

I'll be looking forward your next course :)

Regards

**Comment by hanyelemary** [comment]
Not a problem at all. I'm glad it's working for you now. And thank you for the kind words and the great suggestion. I'll reach out to Safari Books Online to let them know about adding the GitHub link on the page. Best of luck while learning and don't hesitate to reach out if you have questions. Cheers!
